zabbix_image_tag: 6.0.17-alpine


db_access:

  use_unified_secret: false
  unified_secret_name: zabbixdb-pguser-zabbix
  unified_secret_autocreate: false
 
  db_server_host: "postgresql-local.monitoring.svc.cluster.local"
  db_server_port: "5432"
  postgres_user: "diegozbx"

  postgres_password: "ZabbixZabbix"
  postgres_db: "db_zabbix"

zabbixserver:
  enabled: true
  replicaCount: 1
  pod_anti_affinity: true
  hostPort: false
  hostIP: 0.0.0.0
  resources: {}
  image:
    repository: zabbix/zabbix-server-pgsql
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []
  ha_nodes_autoclean:
    enabled: false
    image:
      repository: postgres
      tag: "14"
      pullPolicy: IfNotPresent
      pullSecrets: []
    schedule: "0 1 * * *"
    delete_older_than_seconds: 3600
    extraEnv: []
    extraVolumeMounts: []
    extraContainers: []
    extraInitContainers: []
    extraVolumes: []
    extraPodSpecs: {}
  service:
    type: ClusterIP

    clusterIP:
    port: 10051
    nodePort: 31051
    annotations: {}

  extraEnv:
    - name: "DB_SERVER_SCHEMA"
      value: "zabbix"
  deploymentAnnotations: {}
  containerAnnotations: {}
  extraVolumeMounts: []
  extraContainers: []
  extraInitContainers: []
  extraVolumes: []
  extraPodSpecs: {}

postgresql:
  # -- Create a database using Postgresql
  enabled: false
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
    pullSecrets: []
  persistence:
    enabled: false
    existing_claim_name: false
    storage_size: 5Gi
  service:
    type: ClusterIP
    clusterIP:
    port: 5432
    annotations: {}
  extraRuntimeParameters:
    max_connections: 50
  extraEnv: []
  statefulSetAnnotations: {}
  containerAnnotations: {}
  extraVolumeMounts: []
  extraContainers: []
  extraInitContainers: []
  extraVolumes: []
  extraPodSpecs: {}

zabbixproxy:
  enabled: false
  replicaCount: 1
  resources: {}
  image:
    repository: zabbix/zabbix-proxy-sqlite3
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []
  ZBX_PROXYMODE: 0
  ZBX_HOSTNAME: zabbix-proxy 
  ZBX_SERVER_HOST: zabbix-zabbix-server
  ZBX_SERVER_PORT: 10051
  ZBX_JAVAGATEWAY_ENABLE: false
  ZBX_VMWARECACHESIZE: 128M
  service:
    type: ClusterIP
    clusterIP:
    port: 10051
    annotations: {}
  extraEnv: []
  statefulSetAnnotations: {}
  containerAnnotations: {}
  extraVolumeMounts: []
  extraContainers: []
  extraInitContainers: []
  extraVolumes: []
  extraPodSpecs: {}
  extraVolumeClaimTemplate: []

zabbixagent:
  enabled: false
  resources: {}
  image:
    repository: zabbix/zabbix-agent2
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []
  ZBX_SERVER_HOST: 127.0.0.1
  ZBX_SERVER_PORT: 10051
  ZBX_PASSIVE_ALLOW: true
  ZBX_PASSIVESERVERS: 127.0.0.1
  ZBX_ACTIVE_ALLOW: true


  ZBX_JAVAGATEWAY_ENABLE: false
  ZBX_VMWARECACHESIZE: 128M
  service:
    type: ClusterIP
    clusterIP:
    port: 10050
    annotations: {}
  extraEnv: []
  extraVolumeMounts: []

zabbixweb:
  enabled: true
  replicaCount: 1
  pod_anti_affinity: true
  resources: {}
  image:
    repository: zabbix/zabbix-web-nginx-pgsql
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []

  service:
    type: ClusterIP

    clusterIP:
    port: 80

    annotations: {}
  
  extraEnv:
    - name: "PHP_TZ"
      value: "America/Fortaleza"
    - name: "DB_SERVER_SCHEMA"
      value: "zabbix"

  deploymentAnnotations: {}
  containerAnnotations: {}
  extraVolumeMounts: []
  extraContainers: []
  extraInitContainers: []
  extraVolumes: []
  extraPodSpecs: {}
  livenessProbe:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

zabbixwebservice:
  enabled: false
  replicaCount: 1
  pod_anti_affinity: true
  resources: {}
  image:
    repository: zabbix/zabbix-web-service
    tag: null
    pullPolicy: IfNotPresent
    pullSecrets: []

  service:
    type: ClusterIP
    clusterIP:
    port: 10053
    annotations: {}
    
  extraEnv: []
  deploymentAnnotations: {}
  containerAnnotations: {}
  extraVolumeMounts: []
  extraContainers: []
  extraInitContainers: []
  extraVolumes: []
  extraPodSpecs: {}

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

  pathType: Prefix

ingressroute:
  enabled: false
  annotations: {}
  entryPoints:
    - websecure
  hostName: chart-example.local


route:
  enabled: false
  hostName: chart-example.local
  tls:
    termination: edge
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

karpenter:
  enabled: false
  clusterName: "CHANGE_HERE"
  tag: "karpenter.sh/discovery/CHANGE_HERE: CHANGE_HERE"
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
