{{- if and .Values.zabbixserver.enabled .Values.zabbixserver.ha_nodes_autoclean.enabled }}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "zabbix.fullname" . }}-nodesclean
  labels:
    app: {{ template "zabbix.fullname" . }}-nodesclean
    app.kubernetes.io/name: nodesclean
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-nodesclean
    app.kubernetes.io/managed-by: {{ .Release.Service }}-nodesclean
spec:
  schedule: {{ .Values.zabbixserver.ha_nodes_autoclean.schedule|quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          {{- with .Values.zabbixserver.ha_nodes_autoclean.extraPodSpecs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.zabbixserver.ha_nodes_autoclean.extraInitContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: hanodes-autoclean
            image: {{ .Values.zabbixserver.ha_nodes_autoclean.image.repository }}:{{ .Values.zabbixserver.ha_nodes_autoclean.image.tag }}
            imagePullPolicy: {{ .Values.zabbixserver.ha_nodes_autoclean.image.pullPolicy }}
            command:
            - /bin/bash
            - -c
            - echo "deleting all stopped and unavailable HANodes older than {{ .Values.zabbixserver.ha_nodes_autoclean.delete_older_than_seconds }} seconds..." && psql -c "delete from ha_node where status in (1,2) and extract(epoch from now())-lastaccess>{{ .Values.zabbixserver.ha_nodes_autoclean.delete_older_than_seconds }}"
            env:
            {{- include "zabbix.db_access.env_vars" (list $ . "db_client") | nindent 12 }}
            {{- range $item := .Values.zabbixserver.ha_nodes_autoclean.extraEnv }}
            - name: {{ $item.name }}
              value: {{ $item.value | quote }}
            {{- end }}
            {{- with .Values.zabbixserver.ha_nodes_autoclean.extraVolumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.zabbixserver.ha_nodes_autoclean.extraContainers }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          imagePullSecrets:
          {{- range .Values.zabbixserver.image.pullSecrets }}
            - name: {{ . | quote }}
          {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.zabbixserver.ha_nodes_autoclean.extraVolumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
